name: doxygen-deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy-workflow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Run Doxygen
        working-directory: ${{github.workspace}}/Worksheet5
        run: doxygen

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ${{github.workspace}}/Worksheet5/html